name: cedarmaps
description: A Flutter plugin for integrating Cedarmaps inside a Flutter application on Android, iOS and web platfroms.
version: 0.9.0
homepage: https://github.com/cedarstudios/cedarmaps-flutter-sdk

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/cedarstudios/cedarmaps-flutter-sdk.git
      path: mapbox_gl_platform_interface
  mapbox_gl_web:
    git:
      url: https://github.com/cedarstudios/cedarmaps-flutter-sdk.git
      path: mapbox_gl_web
  http: ^0.12.2

flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.mapboxgl
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
      web:
        default_package: mapbox_gl_web
        
environment:
  sdk: ">=2.1.0 <3.0.0"
  # Flutter versions prior to 1.10 did not support the flutter.plugin.platforms map.
  flutter: ">=1.10.0 <2.0.0"
